[theme]
primaryColor = "#0f3d26"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F7F2"
textColor = "#1A1A1A"
font = "sans serif"
[client]
showSidebarNavigation = false

[server]
enableStaticServing = true
